AWSTemplateFormatVersion: "2010-09-09"
Description: Role for deploying JamSMP resources using Github Actions
Resources:
#  JamsPolicy:
#    Type: AWS::IAM::Policy
#    Properties:
#      PolicyName: JamsDeploy
#      PolicyDocument:
#        Version: "2012-10-17"
#        Statement:
#          - Effect: Allow
#            Action:
#              - 'cloudfront:*'
#              - "s3:GetBucketTagging"
#              - "s3:GetBucketWebsite"
#              - "s3:GetBucketLogging"
#              - "s3:CreateBucket"
#              - "s3:GetBucketVersioning"
#              - "s3:PutBucketCORS"
#              - "s3:GetBucketAcl"
#              - "s3:GetBucketPolicy"
#              - "s3:PutBucketWebsite"
#              - "s3:PutBucketLogging"
#              - "s3:GetBucketCORS"
#              - "s3:PutBucketAcl"
#              - "s3:PutBucketPolicy"
#              - "s3:GetBucketLocation"
#              - "s3:PutObject"
#              - "s3:GetObjectAcl"
#              - "s3:GetObject"
#              - "s3:PutObjectRetention"
#              - "s3:DeleteObjectVersion"
#              - "s3:PutObjectVersionAcl"
#              - "s3:DeleteObject"
#              - "s3:PutObjectAcl"
#
#            Resource:
#              - "arn:aws:s3:::jams-*/*"
#              - "arn:aws:cloudfront::046476997299:distribution/jams-*"
#          - Effect: Allow
#            Action:
#              - 'cloudfront:ListDistributions'
#              - 's3:ListBucket'
#              - 's3:ListAllMyBuckets'
#            Resource: '*'

  JamsDeployRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: arn:aws:iam::046476997299:oidc-provider/token.actions.githubusercontent.com
            Action:
              - sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                "token.actions.githubusercontent.com:sub": "repo:skruger/jamsmp-website:*"
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"

      Policies:
        - PolicyName: "s3-cdn"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudfront:*'
                  - "s3:GetBucketTagging"
                  - "s3:GetBucketWebsite"
                  - "s3:GetBucketLogging"
                  - "s3:CreateBucket"
                  - "s3:GetBucketVersioning"
                  - "s3:PutBucketCORS"
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketPolicy"
                  - "s3:PutBucketWebsite"
                  - "s3:PutBucketLogging"
                  - "s3:GetBucketCORS"
                  - "s3:PutBucketAcl"
                  - "s3:PutBucketPolicy"
                  - "s3:GetBucketLocation"
                  - "s3:PutObject"
                  - "s3:GetObjectAcl"
                  - "s3:GetObject"
                  - "s3:PutObjectRetention"
                  - "s3:DeleteObjectVersion"
                  - "s3:PutObjectVersionAcl"
                  - "s3:DeleteObject"
                  - "s3:PutObjectAcl"

                Resource:
                  - "arn:aws:s3:::jams-*/*"
                  - "arn:aws:s3:::jams-*"
                  - "arn:aws:cloudfront::046476997299:distribution/jams-*"
              - Effect: Allow
                Action:
                  - 'cloudfront:ListDistributions'
                  - 's3:ListBucket'
                  - 's3:ListAllMyBuckets'
                Resource: '*'


