name: JamSMP Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: npm install
      - run: npm build

      - name: Generate artifact
        run: cd dist && zip -r ../dist.zip .

      - uses: actions/upload-artifact@v3
        with:
          name: jamsmp-site
          path: dist.zip
          retention-days: 30
