name: JamSMP Build

env:
  AWS_REGION: us-west-2
  BUCKET_NAME: jams-website

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: npm install
      - run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: JamSMP-website
          path: dist/
          retention-days: 30

  publish:
    runs-on: ubuntu-latest
    needs:
      - build

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: JamSMP-website
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::046476997299:role/Jams-Github-Actions-Role-JamsDeployRole-5RO3AA892JY1
          role-session-name: "jamsmp-website-action-publish"
          aws-region: ${{ env.AWS_REGION }}
      - run: find .
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
        id: extract_branch
      - run: aws s3 sync --acl public-read --no-progress . s3://${{ env.BUCKET_NAME }}/${{ steps.extract_branch.outputs.branch }}/
